# -*- coding: utf-8 -*-
"""bcsample_hundred.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGZ9k1f-PeYQKkenW3aZkmhh-nNlh_eB
"""

import json
import requests

ids = [
    2901, 2905, 2924, 2925, 2926, 2928, 2935, 2938, 3006, 3007,
    3008, 3010, 3017, 3020, 3022, 3023, 3024, 3026, 3029, 3030,
    3035, 3036, 3037, 3039, 3041, 3046, 3047, 3051, 3054, 3055,
    3101, 3102, 3104, 3105, 3110, 3132, 3137, 3143, 3145, 3157,
    3162, 3168, 3169, 3170, 3206, 3208, 3209, 3214, 3215, 3220,
    3221, 3222, 3224, 3229, 3234, 3241, 3242, 3243, 3248, 3252,
    3253, 3254, 3255, 3259, 3263, 3268, 3302, 3303, 3312, 3316,
    3319, 3321, 3323, 3325, 3404, 3408, 3412, 3414, 3417, 3420,
    3422, 3501, 3503, 3514, 3516, 3517, 3520, 3521, 3524, 3530,
    3532, 3536, 3544, 3545, 3550, 3552, 3554, 3556, 3561, 3563
]


print(f"Number of bus IDs: {len(ids)}")

def get_bread_crumbs():
  store_data = []
  for i in ids:
    url = f"https://busdata.cs.pdx.edu/api/getBreadCrumbs?vehicle_id={i}"
    response = requests.get(url)
    # print(response.status_code)
    if response.status_code == 404:
       print(f'id failed {i}')
    else:
      data = response.json()
      store_data.append(data)

  with open(f"bcsample_hundred.json", "w") as f:
    json.dump(store_data, f)

get_bread_crumbs()

