# -*- coding: utf-8 -*-
"""bcsample.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGZ9k1f-PeYQKkenW3aZkmhh-nNlh_eB
"""

!curl "https://busdata.cs.pdx.edu/api/getBreadCrumbs?vehicle_id=2928&vehicle_id=2929" -o bcsample.json

