# -*- coding: utf-8 -*-
"""pub.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGZ9k1f-PeYQKkenW3aZkmhh-nNlh_eB
"""

from google.cloud import pubsub_v1
import json
import time
# TODO(developer)
project_id = "mov-data-eng"
topic_id = "my-topic-1"

publisher = pubsub_v1.PublisherClient()
# The `topic_path` method creates a fully qualified identifier
# in the form `projects/{project_id}/topics/{topic_id}`
topic_path = publisher.topic_path(project_id, topic_id)
count = 0
start_time = time.time()
with open('bcsample.json', 'r') as f:
  jsobj = json.load(f)
  for line in jsobj:
    data = json.dumps(line).encode("utf-8")
    future = publisher.publish(topic_path, data)
   # print(future.result())
    count += 1
end_time = time.time()
print(f"Number of records:{count}")
print("Time taken to run the code:", end_time - start_time, "seconds")