# -*- coding: utf-8 -*-
"""topic_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fGZ9k1f-PeYQKkenW3aZkmhh-nNlh_eB
"""

GNU nano 7.2                                                                             topic_clean.py
#code to clean all messages in subscriber
from google.cloud import pubsub_v1
topic_id = "my-topic-1"
project_id = "mov-data-eng"
subscription_id = "my-sub-1"

subscriber = pubsub_v1.SubscriberClient()
publisher = pubsub_v1.PublisherClient()
topic_path = publisher.topic_path(project_id, topic_id)
subscription_path = subscriber.subscription_path(project_id, subscription_id)

def delete(subscription_path):
  #try and except if there is nothing else to delete
  try:
    subscriber.delete_subscription(request={"subscription": subscription_path})
    print(f"Deleted {subscription_path}.")
  except:
    pass
    print(f"Nothing to delete.")
#recrete subscription
def create(subscription_path):
    subscription = subscriber.create_subscription(
        request={"name": subscription_path, "topic": topic_path}
    )
    print(f"Created subscription {subscription.name}.")


delete(subscription_path)
create(subscription_path)